ColegioColombia.Mvc/Models/Alumno.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColegioColombia.Mvc.Models
{
    [Table("Alumnos")]
    public class Alumno
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "El nombre no puede superar 10 caracteres")]
        public string Nombre { get; set; }

        [Required]
        [MaxLength(10, ErrorMessage = "El nombre no puede superar 10 caracteres")]
        public string Apellido { get; set; }

        [Required]
        public long Cedula { get; set; }

        [Range(6, 11)]
        [Required]
        public int Grado { get; set; }

        [Display(Prompt = "Código del Grupo del Alumno.", Name = "Código del Grupo")]
        public string Grupo { get; set; }
    }
}

ColegioColombia.Mvc/Models/ColegioColombiaMvcContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ColegioColombia.Mvc.Models
{
    public class ColegioColombiaMvcContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        //
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx

        public ColegioColombiaMvcContext() : base("name=ColegioColombiaMvcContext")
        {
            //En Ambientes de desarrollo, para producción se usaría MigrateDatabaseToLatestVersion.
            Database.SetInitializer(
                new DropCreateDatabaseIfModelChanges<ColegioColombiaMvcContext>());
        }

        public System.Data.Entity.DbSet<ColegioColombia.Mvc.Models.Alumno> Alumnoes { get; set; }

        public System.Data.Entity.DbSet<ColegioColombia.Mvc.Models.Profesor> Profesors { get; set; }
    }
}

ColegioColombia.Mvc/Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ColegioColombia.Mvc.Models;

namespace ColegioColombia.Mvc.Controllers
{
    public class AlumnosController : Controller
    {
        private ColegioColombiaMvcContext db = new ColegioColombiaMvcContext();

        // GET: Alumnos
        public ActionResult Index()
        {
            return View(db.Alumnoes.ToList());
        }

        // GET: Alumnos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnoes.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // GET: Alumnos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alumnos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Apellido,Cedula,Grado,Grupo")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                db.Alumnoes.Add(alumno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(alumno);
        }

        // GET: Alumnos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnoes.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // POST: Alumnos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Apellido,Cedula,Grado,Grupo")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alumno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(alumno);
        }

        // GET: Alumnos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnoes.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // POST: Alumnos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alumno alumno = db.Alumnoes.Find(id);
            db.Alumnoes.Remove(alumno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ColegioColombia.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ColegioColombia.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Colegio Colombia";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Colegio Colombia";

            return View();
        }
    }
}

ColegioColombia.Mvc/Controllers/ProfesorController.cs
using ColegioColombia.Mvc.Models;
using ColegioColombia.Mvc.ServicioColombia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ColegioColombia.Mvc.Controllers
{
    public class ProfesorController : Controller
    {
        // GET: Profesor
        public ActionResult Index()
        {
            ViewBag.Bienvenida = "Hola Profesor";
            return View();
        }

        public ActionResult IndexAlterno()
        {
            var modelo = new Profesor();
            modelo.Nombre = "Miguel";
            modelo.Apellido = "Peláez";
            modelo.Cedula = 4587854;

            ServicioColombiaSoapClient servicio = new ServicioColombiaSoapClient();

            ViewBag.SaludoPersonalizado = servicio.SaludoPersonalizado($"{modelo.Nombre} {modelo.Apellido}");

            return View(modelo);
        }
    }
}

ColegioColombia.Mvc/Views/Alumnos/Create.cshtml
@model ColegioColombia.Mvc.Models.Alumno

@{
    ViewBag.Title = "Creaar Alumno";
}

<h2>Crear Alumno</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cr  ear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ColegioColombia.Mvc/Views/Alumnos/Delete.cshtml
@model ColegioColombia.Mvc.Models.Alumno

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar Alumno</h2>

<h3>Esta seguro que desea eliminar el alumno @Html.ValueFor(model => model.Nombre) @Html.ValueFor(model => model.Apellido)?</h3>
<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

ColegioColombia.Mvc/Views/Alumnos/Details.cshtml
@model ColegioColombia.Mvc.Models.Alumno

@{
    ViewBag.Title = "Detalle Alumno";
}

<h2>Ver Detalle del Alumno</h2>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la lista", "Index")
</p>

ColegioColombia.Mvc/Views/Alumnos/Edit.cshtml
@model ColegioColombia.Mvc.Models.Alumno

@{
    ViewBag.Title = "Editar Alumno";
}

<h2>Editar Alumno</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alumno : @Html.ValueFor(model => model.Nombre) @Html.ValueFor(model => model.Apellido)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ColegioColombia.Mvc/Views/Alumnos/Index.cshtml
@model IEnumerable<ColegioColombia.Mvc.Models.Alumno>

@{
    ViewBag.Title = "Lista de Alumnos";
}

<h2>Consulta de Alumnos</h2>

<p>
    @Html.ActionLink("Nuevo Alumno", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grupo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalle", "Details", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

ColegioColombia.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca De";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Todos los derechos reservados.</p>

ColegioColombia.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contactenos";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Sede Medellin<br />
    Calle 12sur # 43 - 11<br />
    <abbr title="Phone">Tel:</abbr>
    (574) 302 5477
</address>

<address>
    Sede Bogotá<br />
    Carrera 11 No. 77A-65<br />
    <abbr title="Phone">Tel:</abbr>
    (571) 646 8444
</address>

<address>
    <strong>Soporte:</strong>   <a href="mailto:soporte@colegiocolombia.com">soporte@colegiocolombia.com</a><br />
    <strong>Admisiones:</strong> <a href="mailto:adminsionesyregistro@colegiocolombia.com">adminsionesyregistro@colegiocolombia.com</a>
</address>

ColegioColombia.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Colegio Colombia</h1>
    <p class="lead">El colegio Colombia es el numero 1 en el ranking a nivel nacional.</p>
    <p><a href="http://www.colegiocolombia.com" class="btn btn-primary btn-lg">Leer mas &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Sedes</h2>
        <p>
            14 sedes distribuidas en todo el territorio Colombiano.
        </p>
        <p>
            <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301948">Conocer las sedes &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Misión</h2>
        <p>
            La I.E. Colegio Colombia tiene una propuesta curricular diversificada, flexible y abierta a la innovación pedagógica, propicia la formación integral de sus estudiantes fundamentada en valores, en la conservación ambiental, en aprender a ser, a conocer, a hacer y a convivir.
        </p>
        <p>
            <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301949">Ver &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Visión</h2>
        <p>
            En el año 2020, La I.E. Colegio Colombia, caracterizada por su diversificación, se perfilará como un escenario educativo de alta calidad y centro de apropiación técnica y tecnológica en el área metropolitana del Valle de Aburrá.
        </p>
        <p>
            <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301950">Ver &raquo;</a>
        </p>
    </div>
</div>

ColegioColombia.Mvc/Views/Profesor/Index.cshtml
@{
    ViewBag.Title = "Lista de Profesores";
}

<h2>@ViewBag.Bienvenida</h2>

@Html.ActionLink("Index Alterno", "IndexAlterno") |

ColegioColombia.Mvc/Views/Profesor/IndexAlterno.cshtml
@model ColegioColombia.Mvc.Models.Profesor

@{
    ViewBag.Title = "IndexAlterno";
}

@*<h2>Hola @Html.DisplayFor(model => model.Nombre) @Html.DisplayFor(model => model.Apellido)</h2>*@
<h2>@ViewBag.SaludoPersonalizado</h2>

    <h4>Su cedula es: @Html.DisplayFor(model => model.Cedula)</h4>

ColegioColombia.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Colegio Colombia", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alumnos", "Index", "Alumnos")</li>
                    <li>@Html.ActionLink("Profesores", "Index", "Profesor")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Colegio Colombia</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>